### ISSUE TITLE
Recognizing Amiibo

### ISSUE THREAD

**Issue by AntoineTurmel** [ModusPwnin/Interactive-Amiibo-Stand#1]
So you are recognizing Amiibo using your own Amiibo unique ID ? I bet that all Link Amiibo shares the same base data for instance ?

**Comment by ModusPwnin** [comment]
I'm sure they do, I just need to figure out where exactly that data is. I think I'm onto something, using the memdump sketch from the Adafruit library. I only have one duplicate Amiibo (Luigi) but it seems like the last 3 characters in the UID it returns are shared. I'm going to try to borrow some more duplicates in a few days and see where that takes me.

**Comment by ModusPwnin** [comment]
Hey, not sure if you'll see this but I figured it out. The Amiibos use MiFare Ultralight cards which have around 126 pages of memory. Pages 21 and 22 seem to be consistent across certain characters and I used that for v3 of the code.

**Comment by AntoineTurmel** [comment]
for two same Mario Amiibo share the same ID ?

**Comment by ModusPwnin** [comment]
Yep, for more information you can look here: http://www.reddit.com/r/amiibros/comments/2p5osa/i_found_the_character_fields_pages_21_22/

**Comment by AntoineTurmel** [comment]
@ModusPwnin nice :)
I'll try to make a mobile app.
